import json
import os
import re
import time

from python.helpers import files
from python.helpers.extension import Extension

# Phrases that indicate an actual architectural/design decision was made.
# These are verb-forward constructions that appear in deliberate decision prose.
_DECISION_PHRASES = [
    "we will use",
    "we chose",
    "chosen approach",
    "decided to",
    "decision:",
    "we are using",
    "we adopted",
    "we moved to",
    "switched to",
    "replaced with",
    "the pattern is",
    "the approach is",
    "going with",
]

# Patterns that indicate the message is internal agent scaffolding, not a real
# decision — these fire frequently and should never generate ADRs.
_SKIP_PATTERNS = [
    r'"thoughts"\s*:',  # JSON thought chain (memory_load, tool_use internals)
    r"memory_load",
    r"I have retrieved",
    r"portfolio manager",  # status-check monologues
    r"The user (has sent|sent|asked)",
]


def _is_real_decision(text: str) -> bool:
    """Return True only if text contains an explicit architectural decision."""
    lower = text.lower()

    # Reject scaffolding noise first
    for pattern in _SKIP_PATTERNS:
        if re.search(pattern, text, re.IGNORECASE):
            return False

    # Require at least one decision phrase
    return any(phrase in lower for phrase in _DECISION_PHRASES)


def _extract_decision_summary(text: str, max_chars: int = 500) -> str:
    """Extract a readable decision summary from the AI message.

    Strips JSON fences, collapses whitespace, and returns the most relevant
    prose passage rather than a raw truncation.
    """
    # Strip markdown code fences
    text = re.sub(r"```[a-z]*\n?", "", text)
    text = re.sub(r"```", "", text)

    # Collapse whitespace runs
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = text.strip()

    # If the text starts with a decision phrase, take from there
    for phrase in _DECISION_PHRASES:
        idx = text.lower().find(phrase)
        if idx != -1:
            # Back up to the start of the sentence (last period before idx)
            sentence_start = text.rfind(". ", 0, idx)
            start = sentence_start + 2 if sentence_start != -1 else 0
            snippet = text[start : start + max_chars].strip()
            if len(text) > start + max_chars:
                snippet += "..."
            return snippet

    # Fallback: first max_chars of cleaned text
    snippet = text[:max_chars]
    if len(text) > max_chars:
        snippet += "..."
    return snippet


class adr_generator(Extension):
    """
    Automated ADR Generator.

    Triggers at the end of a monologue to detect and record genuine
    architectural decisions. Skips scaffolding noise (memory loads,
    status checks, thought-chain dumps) and extracts readable prose
    instead of raw JSON fragments.
    """

    async def execute(self, **kwargs) -> None:
        if not self.agent:
            return

        history = self.agent.history.output()
        if not history:
            return

        last_ai_msg = ""
        for msg in reversed(history):
            if msg.get("ai"):
                content = msg.get("content", "")
                if isinstance(content, str):
                    last_ai_msg = content
                else:
                    last_ai_msg = json.dumps(content, ensure_ascii=False)
                break

        if not _is_real_decision(last_ai_msg):
            return

        try:
            project_name = getattr(self.agent, "agent_name", "A0")
            adr_dir = files.get_abs_path("knowledge/custom/architectural_patterns/adrs")
            os.makedirs(adr_dir, exist_ok=True)

            timestamp = int(time.time())
            filename = f"ADR-{timestamp}.md"
            filepath = os.path.join(adr_dir, filename)

            summary = _extract_decision_summary(last_ai_msg)

            adr_content = f"""# ADR: {timestamp} - {project_name} Decision

## Status

Proposed

## Context

Decided during agent session (monologue end trigger).

## Decision

{summary}

## Consequences

- Recorded in automated knowledge base.
- Available for future RAG retrieval.

---

*Generated by Automated ADR Extension*
"""
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(adr_content)

        except Exception:
            pass  # Silent fail to not disrupt main loop
