"""
API Design Tool

Converted from Mahoosuc OS /api:design command to native Agent Jumbo tool.
Generates API specifications and documentation for resources.

Source: .claude/commands/api/design.md
"""

from python.helpers.tool import Response, Tool


class APIDesign(Tool):
    async def execute(self, **kwargs):
        """
        Generate API design specification for a resource

        Args (from self.args):
            resource: Resource name (e.g., "users", "products", "orders")
            format: Output format (rest/openapi/graphql) - default: rest

        Returns:
            Response with API specification and documentation
        """
        # Get parameters
        resource = self.args.get("resource", "").lower()
        api_format = self.args.get("format", "rest").lower()

        # Validate resource
        if not resource:
            return Response(
                message='Error: resource parameter is required. Example: {"resource": "users"}', break_loop=False
            )

        # Validate format
        valid_formats = ["rest", "openapi", "graphql"]
        if api_format not in valid_formats:
            return Response(
                message=f"Invalid format: {api_format}. Must be one of: {', '.join(valid_formats)}",
                break_loop=False,
            )

        # Generate API design
        if api_format == "rest":
            design = self._generate_rest_design(resource)
        elif api_format == "openapi":
            design = self._generate_openapi_design(resource)
        else:  # graphql
            design = self._generate_graphql_design(resource)

        return Response(message=design, break_loop=False)

    def _generate_rest_design(self, resource: str) -> str:
        """Generate RESTful API design"""
        singular = resource.rstrip("s")

        lines = []
        lines.append(f"# RESTful API Design: {resource.title()}")
        lines.append("")
        lines.append("## Endpoints")
        lines.append("")

        lines.append(f"### List {resource.title()}")
        lines.append(f"**GET** `/api/{resource}`")
        lines.append("")
        lines.append("Query Parameters:")
        lines.append("- `page` (integer): Page number (default: 1)")
        lines.append("- `limit` (integer): Items per page (default: 20)")
        lines.append("- `sort` (string): Sort field (default: created_at)")
        lines.append("")
        lines.append("Response (200 OK):")
        lines.append("```json")
        lines.append("{")
        lines.append(f'  "data": [{{ "id": 1, "name": "Example {singular.title()}" }}],')
        lines.append('  "meta": { "total": 100, "page": 1, "limit": 20 }')
        lines.append("}")
        lines.append("```")
        lines.append("")

        lines.append(f"### Get {singular.title()}")
        lines.append(f"**GET** `/api/{resource}/{{id}}`")
        lines.append("")
        lines.append("Response (200 OK):")
        lines.append("```json")
        lines.append(f'{{ "id": 1, "name": "Example {singular.title()}", "created_at": "2026-01-24" }}')
        lines.append("```")
        lines.append("")

        lines.append(f"### Create {singular.title()}")
        lines.append(f"**POST** `/api/{resource}`")
        lines.append("")
        lines.append("Request Body:")
        lines.append("```json")
        lines.append(f'{{ "name": "New {singular.title()}" }}')
        lines.append("```")
        lines.append("")
        lines.append("Response (201 Created):")
        lines.append("```json")
        lines.append(f'{{ "id": 2, "name": "New {singular.title()}", "created_at": "2026-01-24" }}')
        lines.append("```")
        lines.append("")

        lines.append(f"### Update {singular.title()}")
        lines.append(f"**PUT** `/api/{resource}/{{id}}`")
        lines.append("")
        lines.append("Request Body:")
        lines.append("```json")
        lines.append(f'{{ "name": "Updated {singular.title()}" }}')
        lines.append("```")
        lines.append("")

        lines.append(f"### Delete {singular.title()}")
        lines.append(f"**DELETE** `/api/{resource}/{{id}}`")
        lines.append("")
        lines.append("Response (204 No Content)")
        lines.append("")

        lines.append("## Authentication")
        lines.append("")
        lines.append("All endpoints require Bearer token authentication:")
        lines.append("```")
        lines.append("Authorization: Bearer <token>")
        lines.append("```")
        lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Generated by API Design tool (converted from Mahoosuc OS)*")

        return "\n".join(lines)

    def _generate_openapi_design(self, resource: str) -> str:
        """Generate OpenAPI 3.0 specification"""
        singular = resource.rstrip("s")

        lines = []
        lines.append(f"# OpenAPI Specification: {resource.title()}")
        lines.append("")
        lines.append("```yaml")
        lines.append("openapi: 3.0.0")
        lines.append("info:")
        lines.append(f"  title: {resource.title()} API")
        lines.append("  version: 1.0.0")
        lines.append("paths:")
        lines.append(f"  /{resource}:")
        lines.append("    get:")
        lines.append(f"      summary: List {resource}")
        lines.append("      parameters:")
        lines.append("        - name: page")
        lines.append("          in: query")
        lines.append("          schema:")
        lines.append("            type: integer")
        lines.append("      responses:")
        lines.append("        '200':")
        lines.append(f"          description: List of {resource}")
        lines.append("    post:")
        lines.append(f"      summary: Create {singular}")
        lines.append("      requestBody:")
        lines.append("        required: true")
        lines.append("        content:")
        lines.append("          application/json:")
        lines.append("            schema:")
        lines.append(f"              $ref: '#/components/schemas/{singular.title()}'")
        lines.append("components:")
        lines.append("  schemas:")
        lines.append(f"    {singular.title()}:")
        lines.append("      type: object")
        lines.append("      properties:")
        lines.append("        id:")
        lines.append("          type: integer")
        lines.append("        name:")
        lines.append("          type: string")
        lines.append("```")
        lines.append("")
        lines.append("*Generated by API Design tool (converted from Mahoosuc OS)*")

        return "\n".join(lines)

    def _generate_graphql_design(self, resource: str) -> str:
        """Generate GraphQL schema"""
        singular = resource.rstrip("s")
        type_name = singular.title()

        lines = []
        lines.append(f"# GraphQL Schema: {resource.title()}")
        lines.append("")
        lines.append("```graphql")
        lines.append(f"type {type_name} {{")
        lines.append("  id: ID!")
        lines.append("  name: String!")
        lines.append("  createdAt: DateTime!")
        lines.append("}")
        lines.append("")
        lines.append("type Query {")
        lines.append(f"  {resource}(page: Int, limit: Int): [{type_name}!]!")
        lines.append(f"  {singular}(id: ID!): {type_name}")
        lines.append("}")
        lines.append("")
        lines.append("type Mutation {")
        lines.append(f"  create{type_name}(name: String!): {type_name}!")
        lines.append(f"  update{type_name}(id: ID!, name: String!): {type_name}!")
        lines.append(f"  delete{type_name}(id: ID!): Boolean!")
        lines.append("}")
        lines.append("```")
        lines.append("")
        lines.append("*Generated by API Design tool (converted from Mahoosuc OS)*")

        return "\n".join(lines)
